// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;

module.exports = {
  courseSidebar: [
    'course/intro',
      {
        type: 'category',
        label: '理论',
        link: {type: 'doc', id: 'course/theory/theory'},
        items: [
          'course/theory/L1-1',
          'course/theory/L1-2',
        ],
      },
      {
        type: 'category',
        label: '实践',
        link: {type: 'doc', id: 'course/practice/practice'},
        items: [
          'course/practice/L2-1',
          'course/practice/L2-2',
        ],
      },
      {
        type: 'category',
        label: '作业',
        link: {type: 'doc', id: 'course/assignment/assignment'},
        items: [
          'course/assignment/L3-1',
          'course/assignment/L3-2',
        ],
      },
  ],
  topicSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'topic',
    },
  ],
  resourceSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'resource',
    },
  ],
  // glossarySidebar: [
  //   {
  //     type: 'autogenerated', 
  //     dirName: 'Glossary',
  //   },
  // ],
};